
package gui;

import java.awt.Desktop;
import java.net.URL;
import oop.classes.actors.User;

public class AboutPage extends javax.swing.JFrame {
    private String employeeID; // Changed from int to String
    private String fullName;
    private final String userRole; // Add a field to store the user role
    private User loggedInUser;
    
    
    public AboutPage(User loggedInUser) {
        initComponents();
        this.loggedInUser = loggedInUser;

        if (loggedInUser != null) {
            this.fullName = loggedInUser.getFirstName() + " " + loggedInUser.getLastName();
            // Convert the integer employeeID to a String
            this.employeeID = String.valueOf(loggedInUser.getEmployeeID());
            this.userRole = loggedInUser.getRole();
        } else {
            this.fullName = "";
            this.employeeID = "";
            this.userRole = null;
        }
    }

    
    public AboutPage() {
        initComponents();
        
        backtoemppagePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoemppagePBActionPerformed(evt);
            }
        });
        this.userRole = null;
    }


     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutmainPNL = new javax.swing.JPanel();
        aboutheaderPNL = new javax.swing.JPanel();
        aboutusheaderLBL = new javax.swing.JLabel();
        aboutlogoLBL = new javax.swing.JLabel();
        backtoemppagePB = new javax.swing.JButton();
        secondparLBL = new javax.swing.JLabel();
        firstparLBL = new javax.swing.JLabel();
        offersLP = new javax.swing.JLayeredPane();
        offerspicLBL = new javax.swing.JLabel();
        visitwebPB = new javax.swing.JButton();
        offersLP1 = new javax.swing.JLayeredPane();
        offerspicLBL1 = new javax.swing.JLabel();
        visitwebPB1 = new javax.swing.JButton();
        offersLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aboutmainPNL.setBackground(new java.awt.Color(255, 255, 255));
        aboutmainPNL.setMinimumSize(new java.awt.Dimension(910, 530));
        aboutmainPNL.setPreferredSize(new java.awt.Dimension(910, 530));

        aboutheaderPNL.setBackground(new java.awt.Color(220, 95, 0));
        aboutheaderPNL.setForeground(new java.awt.Color(51, 51, 51));
        aboutheaderPNL.setToolTipText("");

        aboutusheaderLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        aboutusheaderLBL.setForeground(new java.awt.Color(255, 255, 255));
        aboutusheaderLBL.setText("ABOUT MOTORPH");

        aboutlogoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/MPH LOGO 200 X 112.png"))); // NOI18N

        backtoemppagePB.setBackground(new java.awt.Color(204, 0, 0));
        backtoemppagePB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backtoemppagePB.setForeground(new java.awt.Color(255, 255, 255));
        backtoemppagePB.setText("Back");
        backtoemppagePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoemppagePBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutheaderPNLLayout = new javax.swing.GroupLayout(aboutheaderPNL);
        aboutheaderPNL.setLayout(aboutheaderPNLLayout);
        aboutheaderPNLLayout.setHorizontalGroup(
            aboutheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutheaderPNLLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(backtoemppagePB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aboutusheaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(aboutlogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        aboutheaderPNLLayout.setVerticalGroup(
            aboutheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutheaderPNLLayout.createSequentialGroup()
                .addGroup(aboutheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutheaderPNLLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(aboutlogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutheaderPNLLayout.createSequentialGroup()
                        .addGroup(aboutheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(aboutheaderPNLLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backtoemppagePB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, aboutheaderPNLLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(aboutusheaderLBL)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        secondparLBL.setFont(new java.awt.Font("Helvetica", 3, 14)); // NOI18N
        secondparLBL.setForeground(new java.awt.Color(51, 51, 51));
        secondparLBL.setText("Our goal is to be the first choice for Filipinos searching for competitive and affordable motorcycles.");

        firstparLBL.setFont(new java.awt.Font("Helvetica", 3, 14)); // NOI18N
        firstparLBL.setForeground(new java.awt.Color(51, 51, 51));
        firstparLBL.setText("MotorPH was established in 2020 to provide private transportation options to Filipinos. ");

        offersLP.setBackground(new java.awt.Color(204, 204, 204));
        offersLP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        offerspicLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/OFFERS 400 X 252.jpg"))); // NOI18N

        visitwebPB.setFont(new java.awt.Font("Helvetica", 0, 11)); // NOI18N
        visitwebPB.setText("Visit website");
        visitwebPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitwebPBActionPerformed(evt);
            }
        });

        offersLP.setLayer(offerspicLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        offersLP.setLayer(visitwebPB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout offersLPLayout = new javax.swing.GroupLayout(offersLP);
        offersLP.setLayout(offersLPLayout);
        offersLPLayout.setHorizontalGroup(
            offersLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offersLPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(offerspicLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(offersLPLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(visitwebPB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        offersLPLayout.setVerticalGroup(
            offersLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, offersLPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(offerspicLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(visitwebPB)
                .addGap(22, 22, 22))
        );

        offersLP1.setBackground(new java.awt.Color(204, 204, 204));
        offersLP1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        offerspicLBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/DIRECTORY 300 X 165.png"))); // NOI18N
        offerspicLBL1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        visitwebPB1.setFont(new java.awt.Font("Helvetica", 0, 11)); // NOI18N
        visitwebPB1.setText("View Company Directory");
        visitwebPB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitwebPB1ActionPerformed(evt);
            }
        });

        offersLP1.setLayer(offerspicLBL1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        offersLP1.setLayer(visitwebPB1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout offersLP1Layout = new javax.swing.GroupLayout(offersLP1);
        offersLP1.setLayout(offersLP1Layout);
        offersLP1Layout.setHorizontalGroup(
            offersLP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offersLP1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(offerspicLBL1)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, offersLP1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(visitwebPB1)
                .addGap(108, 108, 108))
        );
        offersLP1Layout.setVerticalGroup(
            offersLP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, offersLP1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(offerspicLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visitwebPB1)
                .addGap(22, 22, 22))
        );

        offersLBL.setFont(new java.awt.Font("Helvetica", 2, 14)); // NOI18N
        offersLBL.setForeground(new java.awt.Color(153, 0, 0));
        offersLBL.setText("Offers: Honda, Yamaha, Suzuki, and Kawasaki");

        javax.swing.GroupLayout aboutmainPNLLayout = new javax.swing.GroupLayout(aboutmainPNL);
        aboutmainPNL.setLayout(aboutmainPNLLayout);
        aboutmainPNLLayout.setHorizontalGroup(
            aboutmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutheaderPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(aboutmainPNLLayout.createSequentialGroup()
                .addGroup(aboutmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutmainPNLLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(offersLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(offersLP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutmainPNLLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(offersLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutmainPNLLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(firstparLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutmainPNLLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(secondparLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        aboutmainPNLLayout.setVerticalGroup(
            aboutmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutmainPNLLayout.createSequentialGroup()
                .addComponent(aboutheaderPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(firstparLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondparLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(offersLBL)
                .addGap(18, 18, 18)
                .addGroup(aboutmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(offersLP)
                    .addComponent(offersLP1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutmainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutmainPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visitwebPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitwebPBActionPerformed
        // Visits MotorPH Website ; only accessible by MMDC email
        try {
            // Open the web page URL in the default browser
            Desktop.getDesktop().browse(new URL("https://sites.google.com/mmdc.mcl.edu.ph/motorph/home").toURI());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_visitwebPBActionPerformed

    private void visitwebPB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitwebPB1ActionPerformed
        // Redirects users to clearer picture of company directory
        try {
            // Open the web page URL in the default browser
            Desktop.getDesktop().browse(new URL("https://drive.google.com/file/d/1bawyos_m6El3Eq56N9uhhyG3G7UIGDQF/view?usp=sharing").toURI());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_visitwebPB1ActionPerformed

    private void backtoemppagePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoemppagePBActionPerformed
    // Navigate back based on user role
    if (loggedInUser != null) {
        switch (loggedInUser.getRole()) {
            case "IT":
                AdminIT adminIT = new AdminIT(loggedInUser);
                adminIT.setVisible(true);
                break;
            case "HR":
                AdminHR adminHR = new AdminHR(loggedInUser);
                adminHR.setVisible(true);
                break;
            case "ACCOUNTING":
                AdminAccounting adminAccounting = new AdminAccounting(loggedInUser);
                adminAccounting.setVisible(true);
                break;
            case "IMMEDIATE SUPERVISOR":
                AdminSupervisor adminSupervisor = new AdminSupervisor(loggedInUser);
                adminSupervisor.setVisible(true);
                break;
            case "EMPLOYEE":
                EmployeeSelfService employeeSelfService = new EmployeeSelfService(loggedInUser);
                employeeSelfService.setVisible(true);
                break;
            default:
                // Fallback to generic Admin page if role is unknown
                AdminIT fallback = new AdminIT(loggedInUser);
                fallback.setVisible(true);
                break;
        }
        this.dispose(); // Close the current AboutPage
    } else {
        // If loggedInUser is null, return to login
        new Login().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_backtoemppagePBActionPerformed

   
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Metal".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        AboutPage aboutPage = new AboutPage();
        aboutPage.setLocationRelativeTo(null); // Center the AboutPage
        aboutPage.setVisible(true);
    });
    
    
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutheaderPNL;
    private javax.swing.JLabel aboutlogoLBL;
    private javax.swing.JPanel aboutmainPNL;
    private javax.swing.JLabel aboutusheaderLBL;
    private javax.swing.JButton backtoemppagePB;
    private javax.swing.JLabel firstparLBL;
    private javax.swing.JLabel offersLBL;
    private javax.swing.JLayeredPane offersLP;
    private javax.swing.JLayeredPane offersLP1;
    private javax.swing.JLabel offerspicLBL;
    private javax.swing.JLabel offerspicLBL1;
    private javax.swing.JLabel secondparLBL;
    private javax.swing.JButton visitwebPB;
    private javax.swing.JButton visitwebPB1;
    // End of variables declaration//GEN-END:variables
}
